utils: Update cargo dependencies
Running cargo audit reveals there are some dependencies with
vulnerabilities:

    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 822 security advisories (from /home/hodgesd/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (473 crate dependencies)
Crate:     owning_ref
Version:   0.4.1
Title:     Multiple soundness issues in `owning_ref`
Date:      2022-01-26
ID:        RUSTSEC-2022-0040
URL:       https://rustsec.org/advisories/RUSTSEC-2022-0040
Solution:  No fixed upgrade is available!
Dependency tree:
owning_ref 0.4.1
└── cursive_core 0.3.7
    └── cursive 0.20.0
        └── below-common 0.9.0
            └── cgroupfs 0.9.0
                └── scx_mitosis 0.0.14
Crate:     tracing-subscriber
Version:   0.3.19
Title:     Logging user input may result in poisoning logs with ANSI escape sequences
Date:      2025-08-29
ID:        RUSTSEC-2025-0055
URL:       https://rustsec.org/advisories/RUSTSEC-2025-0055
Solution:  Upgrade to >=0.3.20
Dependency tree:
tracing-subscriber 0.3.19
├── scx_utils 1.0.22
│   ├── scxtop 1.0.19
│   ├── scxcash 0.1.2
│   ├── scx_wd40 1.0.17
│   ├── scx_userspace_arena 1.0.17
│   │   └── scx_chaos 1.0.20
│   ├── scx_tickless 1.0.8
│   ├── scx_rusty 1.0.17
│   ├── scx_rustland_core 2.4.7
│   │   ├── scx_rustland 1.0.17
│   │   └── scx_rlfifo 1.0.17
│   ├── scx_rustland 1.0.17
│   ├── scx_rlfifo 1.0.17
│   ├── scx_raw_pmu 0.1.1
│   │   └── scx_layered 1.0.19
│   ├── scx_p2dq 1.0.22
│   │   └── scx_chaos 1.0.20
│   ├── scx_mitosis 0.0.14
│   ├── scx_layered 1.0.19
│   ├── scx_lavd 1.0.17
│   ├── scx_flash 1.0.15
│   ├── scx_cosmos 1.0.3
│   ├── scx_chaos 1.0.20
│   ├── scx_cargo 1.0.22
│   │   ├── scxtop 1.0.19
│   │   ├── scxcash 0.1.2
│   │   ├── scx_wd40 1.0.17
│   │   ├── scx_userspace_arena 1.0.17
│   │   ├── scx_tickless 1.0.8
│   │   ├── scx_rusty 1.0.17
│   │   ├── scx_rustland 1.0.17
│   │   ├── scx_rlfifo 1.0.17
│   │   ├── scx_p2dq 1.0.22
│   │   ├── scx_mitosis 0.0.14
│   │   ├── scx_layered 1.0.19
│   │   ├── scx_lavd 1.0.17
│   │   ├── scx_flash 1.0.15
│   │   ├── scx_cosmos 1.0.3
│   │   ├── scx_chaos 1.0.20
│   │   ├── scx_bpfland 1.0.17
│   │   ├── scx_bpf_compat 1.0.17
│   │   │   └── scx_layered 1.0.19
│   │   └── scx_arena_selftests 1.0.4
│   ├── scx_bpfland 1.0.17
│   ├── scx_bpf_compat 1.0.17
│   ├── scx_arena_selftests 1.0.4
│   └── scx_arena 0.1.1
│       ├── scx_wd40 1.0.17
│       ├── scx_p2dq 1.0.22
│       └── scx_chaos 1.0.20
└── libbpf-cargo 0.26.0-beta.1
    └── scx_utils 1.0.22
Crate:     paste
Version:   1.0.15
Warning:   unmaintained
Title:     paste - no longer maintained
Date:      2024-10-07
ID:        RUSTSEC-2024-0436
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0436
Dependency tree:
paste 1.0.15
├── scx_utils 1.0.22
│   ├── scxtop 1.0.19
│   ├── scxcash 0.1.2
│   ├── scx_wd40 1.0.17
│   ├── scx_userspace_arena 1.0.17
│   │   └── scx_chaos 1.0.20
│   ├── scx_tickless 1.0.8
│   ├── scx_rusty 1.0.17
│   ├── scx_rustland_core 2.4.7
│   │   ├── scx_rustland 1.0.17
│   │   └── scx_rlfifo 1.0.17
│   ├── scx_rustland 1.0.17
│   ├── scx_rlfifo 1.0.17
│   ├── scx_raw_pmu 0.1.1
│   │   └── scx_layered 1.0.19
│   ├── scx_p2dq 1.0.22
│   │   └── scx_chaos 1.0.20
│   ├── scx_mitosis 0.0.14
│   ├── scx_layered 1.0.19
│   ├── scx_lavd 1.0.17
│   ├── scx_flash 1.0.15
│   ├── scx_cosmos 1.0.3
│   ├── scx_chaos 1.0.20
│   ├── scx_cargo 1.0.22
│   │   ├── scxtop 1.0.19
│   │   ├── scxcash 0.1.2
│   │   ├── scx_wd40 1.0.17
│   │   ├── scx_userspace_arena 1.0.17
│   │   ├── scx_tickless 1.0.8
│   │   ├── scx_rusty 1.0.17
│   │   ├── scx_rustland 1.0.17
│   │   ├── scx_rlfifo 1.0.17
│   │   ├── scx_p2dq 1.0.22
│   │   ├── scx_mitosis 0.0.14
│   │   ├── scx_layered 1.0.19
│   │   ├── scx_lavd 1.0.17
│   │   ├── scx_flash 1.0.15
│   │   ├── scx_cosmos 1.0.3
│   │   ├── scx_chaos 1.0.20
│   │   ├── scx_bpfland 1.0.17
│   │   ├── scx_bpf_compat 1.0.17
│   │   │   └── scx_layered 1.0.19
│   │   └── scx_arena_selftests 1.0.4
│   ├── scx_bpfland 1.0.17
│   ├── scx_bpf_compat 1.0.17
│   ├── scx_arena_selftests 1.0.4
│   └── scx_arena 0.1.1
│       ├── scx_wd40 1.0.17
│       ├── scx_p2dq 1.0.22
│       └── scx_chaos 1.0.20
└── ratatui 0.29.0
    └── scxtop 1.0.19
error: 2 vulnerabilities found!
warning: 1 allowed warning found

Update scx_utils to use a vetted version of the tracing-subscriber
crate.

Signed-off-by: Daniel Hodges <hodgesd@meta.com>